export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_FAILURE = 'GET_QUESTIONS_FAILURE';

export const GET_QUESTION = 'GET_QUESTION';

export const SUBMIT_QUESTIONS_REQUEST = 'SUBMIT_QUESTIONS_REQUEST';
export const SUBMIT_QUESTIONS_SUCCESS = 'SUBMIT_QUESTIONS_SUCCESS';
export const SUBMIT_QUESTIONS_FAILURE = 'SUBMIT_QUESTIONS_FAILURE';

export const ANSWER_QUESTION_REQUEST = 'ANSWER_QUESTION_REQUEST';
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS';
export const ANSWER_QUESTION_FAILURE = 'ANSWER_QUESTION_FAILURE';
